##
## Copyright (c) 2024 BlueRock Security, Inc.
## This software is distributed under the terms of the BedRock Open-Source
## License. See the LICENSE-BedRock file in the repository root for details.
##

trigger:
  rules:
    - if: $DOCKER_RELEASE_MODE == "true"
      when: never
    - if: $CI_PIPELINE_SOURCE =~ /^(merge_request_event|schedule|wep|api)$/
      variables:
        FM_CI_TRIGGER_KIND: mr
    - if: $CI_PIPELINE_SOURCE == 'push' && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        FM_CI_TRIGGER_KIND: default
  variables:
    ORIGIN_CI_COMMIT_SHA: $CI_COMMIT_SHA
    ORIGIN_CI_COMMIT_BRANCH: $CI_COMMIT_BRANCH
    ORIGIN_CI_MERGE_REQUEST_IID: $CI_MERGE_REQUEST_IID
    ORIGIN_CI_MERGE_REQUEST_LABELS: $CI_MERGE_REQUEST_LABELS
    ORIGIN_CI_MERGE_REQUEST_PROJECT_ID: $CI_MERGE_REQUEST_PROJECT_ID
    ORIGIN_CI_MERGE_REQUEST_SOURCE_BRANCH_NAME: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    ORIGIN_CI_MERGE_REQUEST_TARGET_BRANCH_NAME: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    ORIGIN_CI_PIPELINE_SOURCE: $CI_PIPELINE_SOURCE
    ORIGIN_CI_PIPELINE_URL: $CI_PIPELINE_URL
    ORIGIN_CI_PROJECT_PATH: $CI_PROJECT_PATH
    ORIGIN_CI_PROJECT_TITLE: $CI_PROJECT_TITLE
    FM_CI_TRIGGER_KIND: $FM_CI_TRIGGER_KIND
    FM_CI_TRIM_DUNE_CACHE: $FM_CI_TRIM_DUNE_CACHE
    FM_CI_ONLY_FULL_BUILD: $FM_CI_ONLY_FULL_BUILD
    FM_CI_FULL_OPAM: $FM_CI_FULL_OPAM
    FM_CI_DOCKER_OPAM: $FM_CI_DOCKER_OPAM
  trigger:
    project: bedrocksystems/formal-methods/ci-backfire
    branch: main
    strategy: depend

docker-release:
  image: docker:27.3.1
  services:
    - docker:27.3.1-dind
  tags:
    - fm.docker
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $DOCKER_RELEASE_MODE == "true"
  before_script:
    - env
    - docker info
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - make -C docker push-release I_KNOW_WHAT_I_AM_DOING=yes
