# Version configuration (all mandatory).

[versions]
image = "2025-10-03"
main_llvm = 19

# Repository configuration template:
#
# > [repo.<name>]
# > gitlab = "{<gitlab-org>/}?<repo>"
# > branch = "<branch-name>"
# > path = "<path>"
# > deps = ["<name>", ..., "<name>"]
# > vendored = <bool>
#
# Default values are:
# - "gitlab" field: "FM/<name>",
# - "branch" field: "main",
# - "path" field: "./fmdeps/<name>",
# - "deps" field: [],
# - "vendored" field: false.
#
# Typically, the "deps" field includes all direct dependencies only. This is
# not entirely necessary, since transitive dependencies are computed, but it
# is somewhat easier not to mess up.
#
# When the "vendored" field is set, CI uses the repo's "branch" field instead of
# the merge base of the MR's own branch and the repo's "branch" to generate
# comparison data. This is necessary for repositories that need to integrate
# upstream changes which usually cannot be applied cleanly to "branch". The
# corresponding merge bases are generally ancient, incompatible with any other
# of our repos, and thus useless.
# Note that this only fixes *CI* for merge requests with such upstream changes
# but it does not allow us to actually merge such changes through gitlab. The
# corresponding branches must still be force pushed.

[repo.fm-ci]

[repo.rocq]
gitlab = "FM/vendored/rocq"
branch = "br-master"
deps = ["fm-ci"]
path = "./fmdeps/vendored/rocq"
vendored = true

[repo.rocq-stdlib]
gitlab = "FM/vendored/rocq-stdlib"
branch = "br-master"
deps = ["fm-ci", "rocq"]
path = "./fmdeps/vendored/rocq-stdlib"
vendored = true

[repo.stdpp]
gitlab = "FM/vendored/stdpp"
branch = "br-master"
deps = ["fm-ci", "rocq-stdlib"]
path = "./fmdeps/vendored/stdpp"
vendored = true

[repo.iris]
gitlab = "FM/vendored/iris"
branch = "br-master"
deps = ["fm-ci", "stdpp"]
path = "./fmdeps/vendored/iris"
vendored = true

[repo.coq-ext-lib]
gitlab = "FM/vendored/coq-ext-lib"
branch = "br-master"
deps = ["fm-ci", "rocq-stdlib"]
path = "./fmdeps/vendored/coq-ext-lib"
vendored = true

[repo.coq-equations]
gitlab = "FM/vendored/coq-equations"
branch = "br-main"
deps = ["fm-ci", "rocq-stdlib"]
path = "./fmdeps/vendored/coq-equations"
vendored = true

[repo.elpi]
gitlab = "FM/vendored/elpi"
branch = "br-master"
deps = ["fm-ci"]
path = "./fmdeps/vendored/elpi"
vendored = true

[repo.coq-elpi]
gitlab = "FM/vendored/coq-elpi"
branch = "br-master"
deps = ["fm-ci", "rocq-stdlib", "elpi"]
path = "./fmdeps/vendored/coq-elpi"
vendored = true

[repo.coq-lsp]
gitlab = "FM/vendored/coq-lsp"
branch = "br-main"
deps = ["fm-ci", "rocq"]
path = "./fmdeps/vendored/coq-lsp"
vendored = true

[repo.vscoq]
gitlab = "FM/vendored/vscoq"
branch = "br-main"
deps = ["fm-ci", "rocq"]
path = "./fmdeps/vendored/vscoq"
vendored = true

[repo.fm-tools]
deps = ["fm-ci"]

[repo.BRiCk]
branch = "master"
deps = ["fm-ci", "iris", "coq-elpi", "coq-equations"]

[repo.auto]
branch = "master"
deps = ["fm-ci", "BRiCk", "coq-ext-lib"]

[repo.auto-docs]
deps = ["auto"]

[repo.skylabs-fm]
deps = ["auto"]
path = "."

[repo.nova-interface]
gitlab = "FM/bluerock/nova-interface"
deps = ["fm-ci", "auto"]
path = "./bluerock/nova-interface"

[repo.NOVA]
gitlab = "FM/bluerock/NOVA"
branch = "proof"
deps = ["fm-ci", "nova-interface"]
path = "./bluerock/NOVA"

[repo.bhv]
gitlab = "FM/bluerock/bhv"
deps = ["fm-ci", "nova-interface", "NOVA"]
path = "./bluerock/bhv"
