# Version configuration (all mandatory).

[versions]
image = "2025-08-19"
main_llvm = 19

# Repository configuration template:
#
# > [repo.<name>]
# > gitlab = "{<gitlab-org>/}?<repo>"
# > branch = "<branch-name>"
# > path = "<path>"
# > deps = ["<name>", ..., "<name>"]
# > vendored = <bool>
#
# Default values are:
# - "gitlab" field: "formal-methods/<name>",
# - "branch" field: "main",
# - "path" field: "./fmdeps/<name>",
# - "deps" field: [],
# - "vendored" field: false.
#
# Typically, the "deps" field includes all direct dependencies only. This is
# not entirely necessary, since transitive dependencies are computed, but it
# is somewhat easier not to mess up.
#
# When the "vendored" field is set, CI uses the repo's "branch" field instead of
# the merge base of the MR's own branch and the repo's "branch" to generate
# comparison data. This is necessary for repositories that need to integrate
# upstream changes which usually cannot be applied cleanly to "branch". The
# corresponding merge bases are generally ancient, incompatible with any other
# of our repos, and thus useless.
# Note that this only fixes *CI* for merge requests with such upstream changes
# but it does not allow us to actually merge such changes through gitlab. The
# corresponding branches must still be force pushed.

[repo.fm-ci]

[repo.coq]
branch = "br-master"
deps = ["fm-ci"]
vendored = true

[repo.stdlib]
branch = "br-master"
deps = ["fm-ci", "coq"]
vendored = true

[repo.stdpp]
branch = "br-master"
deps = ["fm-ci", "stdlib"]
vendored = true

[repo.iris]
branch = "br-master"
deps = ["fm-ci", "stdpp"]
vendored = true

[repo.coq-ext-lib]
branch = "br-master"
deps = ["fm-ci", "stdlib"]
vendored = true

[repo.coq-equations]
branch = "br-main"
deps = ["fm-ci", "stdlib"]
vendored = true

[repo.elpi]
branch = "br-master"
deps = ["fm-ci"]
vendored = true

[repo.coq-elpi]
branch = "br-master"
deps = ["fm-ci", "stdlib", "elpi"]
vendored = true

[repo.coq-lsp]
branch = "br-main"
deps = ["fm-ci", "coq"]
vendored = true

[repo.vscoq]
branch = "br-main"
deps = ["fm-ci", "coq"]
vendored = true

[repo.fm-tools]
deps = ["fm-ci"]

[repo.cpp2v-core]
gitlab = "cpp2v-core"
branch = "master"
deps = [
  "fm-ci", "iris", "coq-elpi", "coq-equations",
  "coq-ext-lib" # currently redundant, not worth removing
]

[repo.cpp2v]
gitlab = "cpp2v"
branch = "master"
deps = [
  "fm-ci", "cpp2v-core", "coq-ext-lib"
]

[repo.nova-interface]
deps = [
  "fm-ci", "cpp2v"
]

[repo.fm-docs]
branch = "main"
deps = [
  "fm-ci", "cpp2v"
]

[repo.micro-docs]
deps = [
  "cpp2v"
]

[repo.NOVA]
gitlab = "NOVA"
path = "./NOVA"
branch = "proof"
deps = [
  "fm-ci", "cpp2v"
]

[repo.bhv]
gitlab = "bhv"
path = "."
deps = [
  "fm-ci", "cpp2v"
]
