# Version configuration (all mandatory).

[versions]
image = "2025-01-21"
main_llvm = 18
main_swipl = "9.2.7"

# Repository configuration template:
#
# > [repo.<name>]
# > gitlab = "{<gitlab-org>/}?<repo>"
# > branch = "<branch-name>"
# > path = "<path>"
# > deps = ["<name>", ..., "<name>"]
# > vendored = <bool>
#
# Default values are:
# - "gitlab" field: "formal-methods/<name>",
# - "branch" field: "main",
# - "path" field: "./fmdeps/<name>",
# - "deps" field: [],
# - "vendored" field: false.
#
# Typically, the "deps" field includes all direct dependencies only. This is
# not entirely necessary, since transitive dependencies are computed, but it
# is somewhat easier not to mess up.

[repo.fm-ci]

[repo.coq]
branch = "br-master"
deps = ["fm-ci"]
vendored = true

[repo.stdpp]
branch = "br-master"
deps = ["fm-ci", "coq"]
vendored = true

[repo.iris]
branch = "br-master"
deps = ["fm-ci", "coq", "stdpp"]
vendored = true

[repo.coq-ext-lib]
branch = "br-master"
deps = ["fm-ci", "coq"]
vendored = true

[repo.coq-equations]
branch = "br-main"
deps = ["fm-ci", "coq"]
vendored = true

[repo.elpi]
branch = "br-master"
deps = ["fm-ci"]
vendored = true

[repo.coq-elpi]
branch = "br-master"
deps = ["fm-ci", "coq", "elpi"]
vendored = true

[repo.coq-lsp]
branch = "br-main"
deps = ["fm-ci", "coq"]
vendored = true

[repo.vscoq]
branch = "br-main"
deps = ["fm-ci", "coq"]
vendored = true

[repo.cpp2v-core]
gitlab = "cpp2v-core"
branch = "master"
deps = ["fm-ci", "coq", "stdpp", "iris", "coq-elpi"]

[repo.cpp2v]
gitlab = "cpp2v"
branch = "master"
deps = [
  "fm-ci", "coq", "stdpp", "iris", "coq-elpi", "cpp2v-core",
  "coq-equations", "coq-ext-lib"
]

[repo.fm-docs]
branch = "master"
deps = [
  "fm-ci", "coq", "stdpp", "iris", "coq-elpi", "cpp2v-core",
  "coq-equations", "coq-ext-lib", "cpp2v"
]

[repo.NOVA]
gitlab = "NOVA"
path = "./NOVA"
branch = "proof"
deps = [
  "fm-ci", "coq", "stdpp", "iris", "coq-elpi", "cpp2v-core",
  "coq-equations", "coq-ext-lib", "cpp2v"
]

[repo.bhv]
gitlab = "bhv"
path = "."
deps = [
  "fm-ci", "coq", "stdpp", "iris", "coq-elpi", "cpp2v-core",
  "coq-equations", "coq-ext-lib", "cpp2v"
]
