#!/bin/sh
opamPrefix=`opam var prefix`
# To shrink the image, we use opam clean to remove build folders and the repository cache from opam update.
# Some are kept by default because of https://github.com/ocaml/opam/issues/4255
opam clean -a -c --logs -r --untracked --unused-repositories
# -s
