# FROM $BASE_IMAGE
ARG BASE_IMAGE=ghcr.io/skylabsai/workspace:fm-default
FROM $BASE_IMAGE

COPY --chown=coq files/LICENSE /home/coq/LICENSE

COPY files/opam-clean /tmp/files/opam-clean

ARG ROCQ_LOG_PREFIX=bluerock
ARG OPAM_PACKAGES
RUN \
  --mount=type=bind,target=/tmp/workspace.tar,source=files/workspace.tar \
  cd /tmp \
  && tar xf workspace.tar \
  && cd /tmp/workspace \
  && ./fmdeps/fm-ci/docker/opam_build.sh "${ROCQ_LOG_PREFIX}" "${OPAM_PACKAGES}" \
  && sudo rm -rf /tmp/workspace

# Can't be in the previous run command: it fails on workspace.tar
RUN sudo rm -rf /tmp/*
