ARG BASE_IMAGE=ghcr.io/skylabsai/workspace:fm-base
FROM $BASE_IMAGE
ARG DEBIAN_CODENAME=bookworm
### Install LLVM #############################################################

ARG LLVM_MAJ_VER
RUN test -n "${LLVM_MAJ_VER}"

ENV LLVM_VER=${LLVM_MAJ_VER}

RUN echo "deb [trusted=yes] http://apt.llvm.org/${DEBIAN_CODENAME}/ llvm-toolchain-${DEBIAN_CODENAME}-${LLVM_VER} main" \
  | sudo tee -a /etc/apt/sources.list.d/llvm.list

RUN sudo apt-get update -qy \
 && sudo apt-get install -y \
      llvm-${LLVM_VER} libllvm${LLVM_VER} llvm-${LLVM_VER}-dev \
      llvm-${LLVM_VER}-runtime clang-${LLVM_VER} clang-tools-${LLVM_VER} \
      libclang-common-${LLVM_VER}-dev libclang-${LLVM_VER}-dev \
      libclang1-${LLVM_VER} lld-${LLVM_VER} libc++-${LLVM_VER}-dev \
 && sudo apt-get clean \
 && sudo rm -rf /var/lib/apt/lists/*

# Provide standardized location for llvm
RUN sudo ln -s /usr/lib/llvm-${LLVM_VER} /usr/lib/llvm

RUN sudo ln -s /usr/lib/llvm/bin/clang++ /usr/bin/
RUN sudo ln -s ld.lld-${LLVM_VER} /usr/bin/ld.lld

### LLVM Environment setup ########################################################
ENV llvm_base_dir=/usr/lib/llvm/bin
ENV LLVM_BASE_DIR=${llvm_base_dir}/
ENV CC=${LLVM_BASE_DIR}clang
ENV CXX=${LLVM_BASE_DIR}clang++
# Set PATH for both interactive and scripted users.
ENV PATH=${llvm_base_dir}:"$PATH"
RUN echo PATH=${llvm_base_dir}:'"$PATH"' >> ~coq/.profile

### Image versioning environment setup ########################################################

# ARG BR_FMDEPS_VERSION
# RUN test -n "${BR_FMDEPS_VERSION}"

# ARG BR_IMAGE_VERSION
# RUN test -n "${BR_IMAGE_VERSION}"

# ENV DOCKER_IMAGE_VERSION="fmdeps.${BR_FMDEPS_VERSION},llvm.${LLVM_VER},image.${BR_IMAGE_VERSION}"

ARG DOCKER_IMAGE_VERSION
ENV DOCKER_IMAGE_VERSION="${DOCKER_IMAGE_VERSION}"
