ARG BASE_IMAGE=ghcr.io/skylabsai/workspace:fm-ext-deps
FROM $BASE_IMAGE
ARG DEBIAN_CODENAME=bookworm
### Install LLVM #############################################################

ARG LLVM_MAJ_VER
RUN test -n "${LLVM_MAJ_VER}"
ARG LLVM_MAX_VER
RUN test -n "${LLVM_MAX_VER}"

ENV LLVM_VER=${LLVM_MAJ_VER}

RUN \
  let "LLVM_VER == LLVM_MAX_VER" && ver_suffix="" || ver_suffix="-$LLVM_VER" \
  && echo "deb [trusted=yes] http://apt.llvm.org/${DEBIAN_CODENAME}/ llvm-toolchain-${DEBIAN_CODENAME}${ver_suffix} main" \
  | sudo tee -a /etc/apt/sources.list.d/llvm.list

RUN sudo apt-get update -qy \
 && sudo apt-get install -y \
      llvm-${LLVM_VER} libllvm${LLVM_VER} llvm-${LLVM_VER}-dev \
      llvm-${LLVM_VER}-runtime clang-${LLVM_VER} clang-tools-${LLVM_VER} \
      libclang-common-${LLVM_VER}-dev libclang-${LLVM_VER}-dev \
      libclang1-${LLVM_VER} lld-${LLVM_VER} libc++-${LLVM_VER}-dev \
 && sudo apt-get clean \
 && sudo rm -rf /var/lib/apt/lists/*

# Provide standardized location for llvm
RUN sudo ln -s /usr/lib/llvm-${LLVM_VER} /usr/lib/llvm

RUN sudo ln -s /usr/lib/llvm/bin/clang++ /usr/bin/
RUN sudo ln -s ld.lld-${LLVM_VER} /usr/bin/ld.lld

### LLVM Environment setup ########################################################
ENV llvm_base_dir=/usr/lib/llvm/bin
ENV LLVM_BASE_DIR=${llvm_base_dir}/
ENV CC=${LLVM_BASE_DIR}clang
ENV CXX=${LLVM_BASE_DIR}clang++
# Set PATH for both interactive and scripted users.
ENV PATH=${llvm_base_dir}:"$PATH"
RUN echo PATH=${llvm_base_dir}:'"$PATH"' >> ~coq/.profile
