ARG BASE_IMAGE=ghcr.io/skylabsai/workspace:fm-os
FROM $BASE_IMAGE

USER root

# https://docs.docker.com/engine/install/debian/#install-using-the-repository
RUN set -x \
  && apt-get update \
  && apt-get install -y gpg \
  && install -m 0755 -d /etc/apt/keyrings \
  && curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc \
  && chmod a+r /etc/apt/keyrings/docker.asc \
  && echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
    $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
    tee /etc/apt/sources.list.d/docker.list > /dev/null \
  && apt-get update

RUN set -x \
  && apt-get install --no-install-recommends -y docker-ce-cli docker-buildx-plugin
  # && apt-get clean \
  # && rm -rf /var/lib/apt/lists/*
# docker-compose-plugin
# docker-ce containerd.io

RUN groupadd -g 988 docker && adduser coq docker

USER coq
