# BSD 3-Clause License (from https://github.com/coq-community/docker-base)
# (Not much is left from the original though.)
# https://github.com/coq-community/docker-base/blob/master/base/bare/Dockerfile
# https://github.com/coq-community/docker-base/blob/master/LICENSE
FROM debian:bookworm

SHELL ["/bin/bash", "--login", "-o", "pipefail", "-c"]

CMD ["/bin/bash", "--login"]

# Supports bash-isms better, for instance for cram tests
# (see https://bluerocksecurity.atlassian.net/browse/FM-4754)
RUN ln -sf bash /bin/sh

### Install uv

COPY --from=ghcr.io/astral-sh/uv:0.9.11 /uv /uvx /bin/

### Install system packages ##################################################

ENV DEBIAN_FRONTEND=noninteractive

# hadolint ignore=DL3008
RUN apt-get update -y -q \
 && apt-get install -y -q --no-install-recommends \
      build-essential ca-certificates curl git git-lfs m4 \
      openssh-client pkg-config rsync sudo time \
      bsdmainutils zip unzip zlib1g-dev \
      libpcre3-dev \
      less moreutils \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# libpcre3-dev is for opam patdiff

### Add Coq group and user with sudo perms ###################################

RUN groupadd -g 1008 coq \
 && useradd --no-log-init -m -s /bin/bash -g coq -G sudo -p '' -u 1008 coq

WORKDIR /home/coq
USER coq

RUN mkdir -p -v /home/coq/bin /home/coq/.local/bin

# config
ENV PATH="/home/coq/.local/bin:${PATH}"
